export type TranslationLanguage = 'en' | 'hi' | 'mr';
export type TranslationDictionary = Record<string, string>;

const en: TranslationDictionary = {
  'registration.step.language': 'Language', 'registration.step.voice': 'Voice Setup', 'registration.step.consent': 'Consent', 'registration.step.identity': 'Identity', 'registration.step.health': 'Health', 'registration.step.history': 'History', 'registration.step.documents': 'Documents', 'registration.step.abha': 'ABHA', 'registration.step.review': 'Review', 'registration.step.token': 'Token Slip',
  'registration.identity.title': 'Patient Personal & Demographics Details', 'registration.identity.subtitle': 'Touch to type or speak into any field. Real-time duplicate detection protects your existing file.', 'registration.identity.fullName': 'Full Name', 'registration.identity.gender': 'Gender', 'registration.identity.dateOfBirth': 'Date of Birth', 'registration.identity.age': 'Age (Years)', 'registration.identity.mobile': 'Mobile Number', 'registration.identity.email': 'Email Address', 'registration.identity.address': 'Residential Address', 'registration.identity.pincode': 'PIN Code', 'registration.identity.emergencyName': 'Emergency Contact Name', 'registration.identity.emergencyRelation': 'Relationship', 'registration.identity.emergencyPhone': 'Emergency Contact Number', 'registration.identity.male': 'Male', 'registration.identity.female': 'Female', 'registration.identity.other': 'Other', 'registration.identity.continue': 'Continue to Health Questions', 'registration.identity.duplicate': 'Existing Hospital Patient Record Found!', 'registration.identity.openFile': 'Open Existing Patient File', 'registration.identity.newVisit': 'Continue as New Visit / Registration', 'common.back': 'Back', 'common.continue': 'Continue', 'common.next': 'Next', 'common.cancel': 'Cancel', 'common.confirm': 'Confirm', 'common.submit': 'Submit', 'common.edit': 'Edit', 'common.readAgain': 'Read Again',
};

const hi: TranslationDictionary = {
  'registration.step.language': 'भाषा', 'registration.step.voice': 'वॉयस सेटअप', 'registration.step.consent': 'सहमति', 'registration.step.identity': 'पहचान', 'registration.step.health': 'स्वास्थ्य', 'registration.step.history': 'इतिहास', 'registration.step.documents': 'दस्तावेज़', 'registration.step.abha': 'आभा', 'registration.step.review': 'समीक्षा', 'registration.step.token': 'टोकन पर्ची',
  'registration.identity.title': 'मरीज की व्यक्तिगत और जनसांख्यिकीय जानकारी', 'registration.identity.subtitle': 'किसी भी क्षेत्र में टाइप करें या बोलकर जानकारी दें। डुप्लिकेट जांच आपकी मौजूदा फाइल को सुरक्षित रखती है।', 'registration.identity.fullName': 'पूरा नाम', 'registration.identity.gender': 'लिंग', 'registration.identity.dateOfBirth': 'जन्म तिथि', 'registration.identity.age': 'आयु (वर्ष)', 'registration.identity.mobile': 'मोबाइल नंबर', 'registration.identity.email': 'ईमेल पता', 'registration.identity.address': 'निवास का पता', 'registration.identity.pincode': 'पिन कोड', 'registration.identity.emergencyName': 'आपातकालीन संपर्क का नाम', 'registration.identity.emergencyRelation': 'रिश्ता', 'registration.identity.emergencyPhone': 'आपातकालीन संपर्क नंबर', 'registration.identity.male': 'पुरुष', 'registration.identity.female': 'महिला', 'registration.identity.other': 'अन्य', 'registration.identity.continue': 'स्वास्थ्य प्रश्नों पर जाएं', 'registration.identity.duplicate': 'अस्पताल का मौजूदा मरीज रिकॉर्ड मिला!', 'registration.identity.openFile': 'मौजूदा मरीज की फाइल खोलें', 'registration.identity.newVisit': 'नई यात्रा / पंजीकरण के रूप में जारी रखें', 'common.back': 'पीछे', 'common.continue': 'जारी रखें', 'common.next': 'आगे', 'common.cancel': 'रद्द करें', 'common.confirm': 'पुष्टि करें', 'common.submit': 'जमा करें', 'common.edit': 'संपादित करें', 'common.readAgain': 'फिर से पढ़ें',
};

const mr: TranslationDictionary = {
  'registration.step.language': 'भाषा', 'registration.step.voice': 'आवाज सेटअप', 'registration.step.consent': 'संमती', 'registration.step.identity': 'ओळख', 'registration.step.health': 'आरोग्य', 'registration.step.history': 'वैद्यकीय इतिहास', 'registration.step.documents': 'कागदपत्रे', 'registration.step.abha': 'आभा', 'registration.step.review': 'आढावा', 'registration.step.token': 'टोकन पावती',
  'registration.identity.title': 'रुग्णाची वैयक्तिक आणि लोकसंख्याशास्त्रीय माहिती', 'registration.identity.subtitle': 'कोणत्याही क्षेत्रात टाइप करा किंवा बोलून माहिती द्या. डुप्लिकेट तपासणी तुमची विद्यमान फाइल सुरक्षित ठेवते.', 'registration.identity.fullName': 'पूर्ण नाव', 'registration.identity.gender': 'लिंग', 'registration.identity.dateOfBirth': 'जन्मतारीख', 'registration.identity.age': 'वय (वर्षे)', 'registration.identity.mobile': 'मोबाईल क्रमांक', 'registration.identity.email': 'ईमेल पत्ता', 'registration.identity.address': 'निवासी पत्ता', 'registration.identity.pincode': 'पिन कोड', 'registration.identity.emergencyName': 'आपत्कालीन संपर्काचे नाव', 'registration.identity.emergencyRelation': 'नाते', 'registration.identity.emergencyPhone': 'आपत्कालीन संपर्क क्रमांक', 'registration.identity.male': 'पुरुष', 'registration.identity.female': 'स्त्री', 'registration.identity.other': 'इतर', 'registration.identity.continue': 'आरोग्य प्रश्नांकडे जा', 'registration.identity.duplicate': 'रुग्णालयातील विद्यमान रुग्णाची नोंद सापडली!', 'registration.identity.openFile': 'विद्यमान रुग्णाची फाइल उघडा', 'registration.identity.newVisit': 'नवीन भेट / नोंदणी म्हणून पुढे जा', 'common.back': 'मागे', 'common.continue': 'पुढे जा', 'common.next': 'पुढे', 'common.cancel': 'रद्द करा', 'common.confirm': 'पुष्टी करा', 'common.submit': 'सबमिट करा', 'common.edit': 'संपादित करा', 'common.readAgain': 'पुन्हा वाचा',
};

Object.assign(en, {
  'registration.language.title': 'Choose Your Language', 'registration.voice.title': 'Voice Assistant & Microphone Verification', 'registration.consent.title': 'Patient Information Sheet & Written Consent Form', 'registration.health.title': 'Reason for Visit & Symptom Assessment', 'registration.history.title': 'Medical History, Allergies & Prescriptions', 'registration.documents.title': 'Document Scanning & OCR Verification', 'registration.abha.title': 'ABHA ID Linkage & National Health Account', 'registration.review.title': 'Review Registration Information', 'registration.token.title': 'Registration Complete', 'registration.question.language': 'Please select your preferred language.', 'registration.question.voice': 'Would you like voice assistance?', 'registration.question.consent': 'Please review the consent information and confirm your choice.', 'registration.question.identity': 'Please provide your patient identity and contact details.', 'registration.question.health': 'What health problem are you experiencing today?', 'registration.question.history': 'Please tell me about your medical history, allergies, and medicines.', 'registration.question.documents': 'Please upload or scan a medical document if you have one.', 'registration.question.abha': 'Do you have an ABHA number?', 'registration.question.review': 'Please review your registration information before confirming.', 'registration.question.token': 'Your registration is complete. Please note your token number.', 'registration.question.fullName': 'Please tell me your full name.', 'registration.question.dateOfBirth': 'Please tell me your date of birth.', 'registration.question.gender': 'What is your gender?', 'registration.question.mobile': 'Please tell me your mobile number.', 'registration.question.email': 'Please tell me your email address, or say skip.', 'registration.question.pincode': 'Please tell me your PIN code.', 'registration.question.address': 'Please tell me your residential address.', 'registration.question.emergencyName': 'Please tell me your emergency contact name.', 'registration.question.emergencyRelation': 'What is your relationship with this emergency contact?', 'registration.question.emergencyPhone': 'Please tell me your emergency contact number.', 'registration.answer.confirm': 'You said {answer}. Is that correct? Say yes or no.', 'registration.answer.empty': 'I did not hear an answer. Please try again.', 'registration.answer.invalid': 'That answer could not be understood. Please try again.',
});
Object.assign(hi, {
  'registration.language.title': 'अपनी भाषा चुनें', 'registration.voice.title': 'वॉयस सहायक और माइक्रोफोन सत्यापन', 'registration.consent.title': 'मरीज सूचना पत्र और लिखित सहमति प्रपत्र', 'registration.health.title': 'आने का कारण और लक्षणों का आकलन', 'registration.history.title': 'चिकित्सा इतिहास, एलर्जी और दवाएं', 'registration.documents.title': 'दस्तावेज़ स्कैनिंग और OCR सत्यापन', 'registration.abha.title': 'आभा आईडी लिंक और राष्ट्रीय स्वास्थ्य खाता', 'registration.review.title': 'पंजीकरण जानकारी की समीक्षा', 'registration.token.title': 'पंजीकरण पूरा हुआ', 'registration.question.language': 'कृपया अपनी पसंदीदा भाषा चुनें।', 'registration.question.voice': 'क्या आप वॉयस सहायता चाहते हैं?', 'registration.question.consent': 'कृपया सहमति की जानकारी पढ़ें और अपनी पसंद की पुष्टि करें।', 'registration.question.identity': 'कृपया अपनी पहचान और संपर्क जानकारी दें।', 'registration.question.health': 'आज आपको कौन सी स्वास्थ्य समस्या हो रही है?', 'registration.question.history': 'कृपया अपने चिकित्सा इतिहास, एलर्जी और दवाओं के बारे में बताएं।', 'registration.question.documents': 'यदि आपके पास कोई चिकित्सा दस्तावेज़ है, तो उसे अपलोड या स्कैन करें।', 'registration.question.abha': 'क्या आपके पास आभा नंबर है?', 'registration.question.review': 'पुष्टि करने से पहले अपनी पंजीकरण जानकारी की समीक्षा करें।', 'registration.question.token': 'आपका पंजीकरण पूरा हो गया है। कृपया अपना टोकन नंबर ध्यान रखें।',
});
Object.assign(mr, {
  'registration.language.title': 'आपली भाषा निवडा', 'registration.voice.title': 'आवाज सहाय्यक आणि मायक्रोफोन पडताळणी', 'registration.consent.title': 'रुग्ण माहिती पत्र आणि लेखी संमती अर्ज', 'registration.health.title': 'येण्याचे कारण आणि लक्षणांचे मूल्यांकन', 'registration.history.title': 'वैद्यकीय इतिहास, ॲलर्जी आणि औषधे', 'registration.documents.title': 'कागदपत्र स्कॅनिंग आणि OCR पडताळणी', 'registration.abha.title': 'आभा आयडी लिंक आणि राष्ट्रीय आरोग्य खाते', 'registration.review.title': 'नोंदणी माहितीचा आढावा', 'registration.token.title': 'नोंदणी पूर्ण झाली', 'registration.question.language': 'कृपया आपली आवडती भाषा निवडा.', 'registration.question.voice': 'आपल्याला आवाज सहाय्यक हवा आहे का?', 'registration.question.consent': 'कृपया संमतीची माहिती वाचा आणि आपल्या निवडीची पुष्टी करा.', 'registration.question.identity': 'कृपया आपली ओळख आणि संपर्क माहिती द्या.', 'registration.question.health': 'आज आपल्याला कोणती आरोग्य समस्या जाणवत आहे?', 'registration.question.history': 'कृपया आपला वैद्यकीय इतिहास, ॲलर्जी आणि औषधांबद्दल सांगा.', 'registration.question.documents': 'आपल्याकडे वैद्यकीय कागदपत्र असल्यास ते अपलोड किंवा स्कॅन करा.', 'registration.question.abha': 'आपल्याकडे आभा क्रमांक आहे का?', 'registration.question.review': 'पुष्टी करण्यापूर्वी आपल्या नोंदणी माहितीचा आढावा घ्या.', 'registration.question.token': 'आपली नोंदणी पूर्ण झाली आहे. कृपया आपला टोकन क्रमांक लक्षात ठेवा.',
});

Object.assign(hi, {
  'registration.question.fullName': 'कृपया अपना पूरा नाम बताइए।', 'registration.question.dateOfBirth': 'कृपया अपनी जन्मतिथि बताइए।', 'registration.question.gender': 'आपका लिंग क्या है?', 'registration.question.mobile': 'कृपया अपना मोबाइल नंबर बताइए।', 'registration.question.email': 'कृपया अपना ईमेल पता बताइए या छोड़ें कहें।', 'registration.question.pincode': 'कृपया अपना पिन कोड बताइए।', 'registration.question.address': 'कृपया अपना निवास का पता बताइए।', 'registration.question.emergencyName': 'कृपया अपने आपातकालीन संपर्क का नाम बताइए।', 'registration.question.emergencyRelation': 'आपातकालीन संपर्क का आपके साथ क्या रिश्ता है?', 'registration.question.emergencyPhone': 'कृपया आपातकालीन संपर्क नंबर बताइए।', 'registration.answer.confirm': 'आपने {answer} कहा। क्या यह सही है? हाँ या नहीं कहें।', 'registration.answer.empty': 'मुझे उत्तर सुनाई नहीं दिया। कृपया फिर से कोशिश करें।', 'registration.answer.invalid': 'उत्तर समझ में नहीं आया। कृपया फिर से कोशिश करें।',
});
Object.assign(mr, {
  'registration.question.fullName': 'कृपया आपले पूर्ण नाव सांगा.', 'registration.question.dateOfBirth': 'कृपया आपली जन्मतारीख सांगा.', 'registration.question.gender': 'आपले लिंग काय आहे?', 'registration.question.mobile': 'कृपया आपला मोबाईल क्रमांक सांगा.', 'registration.question.email': 'कृपया आपला ईमेल पत्ता सांगा किंवा वगळा असे म्हणा.', 'registration.question.pincode': 'कृपया आपला पिन कोड सांगा.', 'registration.question.address': 'कृपया आपला निवासी पत्ता सांगा.', 'registration.question.emergencyName': 'कृपया आपल्या आपत्कालीन संपर्काचे नाव सांगा.', 'registration.question.emergencyRelation': 'आपत्कालीन संपर्काचे आपल्याशी कोणते नाते आहे?', 'registration.question.emergencyPhone': 'कृपया आपत्कालीन संपर्क क्रमांक सांगा.', 'registration.answer.confirm': 'आपण {answer} असे सांगितले. हे बरोबर आहे का? हो किंवा नाही म्हणा.', 'registration.answer.empty': 'मला उत्तर ऐकू आले नाही. कृपया पुन्हा प्रयत्न करा.', 'registration.answer.invalid': 'उत्तर समजले नाही. कृपया पुन्हा प्रयत्न करा.',
});

export const translations: Record<TranslationLanguage, TranslationDictionary> = { en, hi, mr };